name: 'Notify failures to team'
description: 'Centralized action to notify failures to team (Currently by Google Meet)'
runs:
  using: "composite"
  steps:
    - name: Google Chat Notifications
      uses: SimonScholz/google-chat-action@main
      if: failure()
      # this allows the build to succeed even when the notification fails
      # e.g. due to dependabot push, which may not have the secret
      continue-on-error: true
      with:
        # https://docs.github.com/en/webhooks/webhook-events-and-payloads
        webhookUrl: ${{ secrets.WEBHOOK_ALERTES_WEBAPPS }}
        jobStatus: ${{ job.status }}
        imageUrl: ${{ format('https://github.com/{0}.png', github.event.head_commit.author.username) }}
        imageAltText: ${{ github.event.head_commit.author.name }}
        subtitle: ${{ github.event.head_commit.message }}
        title: "${{ format('{0} -- [{1}]', github.event.repository.name, github.event.ref) }}"

