name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install JS dependencies
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm run dev

      - name: Google Chat Notificationa
        uses: SimonScholz/google-chat-action@main
        if: failure()
        # this allows the build to succeed even when the notification fails
        # e.g. due to dependabot push, which may not have the secret
        continue-on-error: true
        with:
          # https://docs.github.com/en/webhooks/webhook-events-and-payloads
          webhookUrl: ${{ secrets.WEBHOOK_ALERTES_WEBAPPS }}
          jobStatus: ${{ job.status }}
          imageUrl: ${{ format('https://github.com/{0}.png', github.event.head_commit.author.username) }}
          imageAltText: ${{ github.event.head_commit.author.name }}
          subtitle: ${{ github.event.head_commit.message }}
          title: "${{ format('{0} -- [{1}]', github.event.repository.name, github.event.ref) }}"

