name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set environment variables
        run: |
          echo "VITE_APP_API_BASE_URL=${{ secrets.VITE_APP_API_BASE_URL }}" >> $GITHUB_ENV && \
          echo "VITE_APP_PLAUSIBLE_TRACK_DOMAIN=localhost" >> $GITHUB_ENV && \
          echo "VITE_APP_PLAUSIBLE_APIHOST_URL=${{ secrets.VITE_APP_PLAUSIBLE_APIHOST_URL }}" >> $GITHUB_ENV
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install JS dependencies
        run: |
          npm cache clean --force
          npm install
      - name: Run vitest
        run: TZ=Europe/Madrid vitest run
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm run dev

      - uses: ./.github/actions/action-notify-failures-to-team
        continue-on-error: true
        if: failure()
